#!/usr/bin/env python3
"""Generate publication-quality Fisher diagnostic figures from audited values."""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import pandas as pd


GROUP_ORDER = [
    "encoder_mlp",
    "encoder_attention_qkv",
    "encoder_attention_proj",
    "final_heads",
    "decoder_nt",
    "decoder_conv_like",
]

GROUP_LABELS = {
    "final_heads": "final heads",
    "decoder_nt": "decoder NT",
    "decoder_conv_like": "decoder conv",
    "encoder_attention_qkv": "attn QKV",
    "encoder_attention_proj": "attn proj",
    "encoder_mlp": "encoder MLP",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--audit-csv",
        type=Path,
        default=Path("reports/fisher_interpretation_audit_values.csv"),
        help="CSV generated by the Fisher interpretation audit.",
    )
    parser.add_argument(
        "--fig-dir",
        type=Path,
        default=Path("figures"),
        help="Directory for PDF/PNG outputs.",
    )
    parser.add_argument(
        "--report",
        type=Path,
        default=Path("reports/fisher_figures_summary.md"),
        help="Markdown summary with captions and paper text.",
    )
    return parser.parse_args()


def clean_axes(ax) -> None:
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    ax.grid(axis="x", color="0.88", linewidth=0.6)
    ax.set_axisbelow(True)


def save(fig, prefix: Path) -> None:
    prefix.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(prefix.with_suffix(".pdf"), bbox_inches="tight")
    fig.savefig(prefix.with_suffix(".png"), dpi=450, bbox_inches="tight")


def load_focus(audit_csv: Path) -> pd.DataFrame:
    df = pd.read_csv(audit_csv)
    missing = [group for group in GROUP_ORDER if group not in set(df["group"])]
    if missing:
        raise ValueError(f"Missing required groups in {audit_csv}: {missing}")
    out = df.set_index("group").loc[GROUP_ORDER].reset_index()
    out["label"] = out["group"].map(GROUP_LABELS)
    return out


def figure_a(df: pd.DataFrame, out_prefix: Path) -> None:
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    plt.rcParams.update(
        {
            "font.size": 8,
            "axes.titlesize": 8.5,
            "axes.labelsize": 8,
            "xtick.labelsize": 7.5,
            "ytick.labelsize": 7.5,
            "legend.fontsize": 7,
            "pdf.fonttype": 42,
            "ps.fonttype": 42,
        }
    )

    y = np.arange(len(df))
    labels = df["label"].tolist()
    encoder_color = "#4C78A8"
    decoder_color = "#72B7B2"
    head_color = "#F58518"
    colors = [
        head_color if group == "final_heads" else decoder_color if group.startswith("decoder") else encoder_color
        for group in df["group"]
    ]

    fig, axes = plt.subplots(
        1,
        3,
        figsize=(7.1, 2.35),
        gridspec_kw={"width_ratios": [1.05, 1.05, 1.35], "wspace": 0.34},
    )

    # Panel 1: total Fisher mass share.
    ax = axes[0]
    vals = df["fisher_mass_percent_ckpt10"].to_numpy()
    ax.barh(y, vals, color=colors, edgecolor="0.25", linewidth=0.35)
    ax.set_yticks(y)
    ax.set_yticklabels(labels)
    ax.invert_yaxis()
    ax.set_xlabel("Fisher mass (%)")
    ax.set_title("(a) total mass")
    ax.set_xlim(0, max(vals) * 1.18)
    for yi, value in enumerate(vals):
        ax.text(value + max(vals) * 0.025, yi, f"{value:.1f}", va="center", fontsize=7)
    clean_axes(ax)

    # Panel 2: Fisher mass per parameter.
    ax = axes[1]
    vals = df["fisher_mean_x1e5_ckpt10"].to_numpy()
    ax.barh(y, vals, color=colors, edgecolor="0.25", linewidth=0.35)
    ax.set_yticks(y)
    ax.set_yticklabels([])
    ax.invert_yaxis()
    ax.set_xlabel(r"$10^5\,\mu_g$")
    ax.set_title("(b) per parameter")
    ax.set_xlim(0, max(vals) * 1.20)
    for yi, value in enumerate(vals):
        label = f"{value:.2f}" if value >= 1 else f"{value:.3f}"
        ax.text(value + max(vals) * 0.025, yi, label, va="center", fontsize=7)
    clean_axes(ax)

    # Panel 3: JS drift per parameter for both transitions.
    ax = axes[2]
    h = 0.34
    vals_15 = df["js_per_param_x1e7_1_to_5"].to_numpy()
    vals_510 = df["js_per_param_x1e7_5_to_10"].to_numpy()
    ax.barh(y - h / 2, vals_15, height=h, color="#A0CBE8", edgecolor="0.25", linewidth=0.25, label="1→5")
    ax.barh(y + h / 2, vals_510, height=h, color="#FFBE7D", edgecolor="0.25", linewidth=0.25, label="5→10")
    ax.set_yticks(y)
    ax.set_yticklabels([])
    ax.invert_yaxis()
    ax.set_xlabel(r"$10^7\,d_{\mathrm{JS}}/N_g$")
    ax.set_title("(c) drift per parameter")
    ax.set_xlim(0, max(vals_15.max(), vals_510.max()) * 1.22)
    for yi, (v1, v2) in enumerate(zip(vals_15, vals_510)):
        ax.text(v1 + max(vals_15.max(), vals_510.max()) * 0.02, yi - h / 2, f"{v1:.2f}" if v1 >= 1 else f"{v1:.3f}", va="center", fontsize=6.7)
        ax.text(v2 + max(vals_15.max(), vals_510.max()) * 0.02, yi + h / 2, f"{v2:.2f}" if v2 >= 1 else f"{v2:.3f}", va="center", fontsize=6.7)
    ax.legend(frameon=False, loc="lower right", borderaxespad=0.2)
    clean_axes(ax)

    save(fig, out_prefix)
    plt.close(fig)


def figure_b(df: pd.DataFrame, out_prefix: Path) -> None:
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    from matplotlib.colors import Normalize

    plt.rcParams.update(
        {
            "font.size": 8,
            "axes.titlesize": 8.5,
            "xtick.labelsize": 7.2,
            "ytick.labelsize": 7.5,
            "pdf.fonttype": 42,
            "ps.fonttype": 42,
        }
    )

    cols = [
        ("fisher_mass_percent_ckpt10", "mass %"),
        ("fisher_mean_x1e5_ckpt10", r"$10^5\mu_g$"),
        ("js_drift_1_to_5", "JS 1→5"),
        ("js_drift_5_to_10", "JS 5→10"),
        ("js_per_param_x1e7_1_to_5", r"$10^7$ JS/N 1→5"),
        ("js_per_param_x1e7_5_to_10", r"$10^7$ JS/N 5→10"),
    ]
    data = df[[c for c, _ in cols]].to_numpy(dtype=float)
    display = np.zeros_like(data)
    for j in range(data.shape[1]):
        col = data[:, j]
        lo, hi = float(np.nanmin(col)), float(np.nanmax(col))
        display[:, j] = (col - lo) / (hi - lo) if hi > lo else 1.0

    fig, ax = plt.subplots(figsize=(7.0, 2.35))
    im = ax.imshow(display, cmap="viridis", aspect="auto", norm=Normalize(0, 1))
    ax.set_yticks(np.arange(len(df)))
    ax.set_yticklabels(df["label"])
    ax.set_xticks(np.arange(len(cols)))
    ax.set_xticklabels([label for _, label in cols], rotation=25, ha="right")
    ax.tick_params(length=0)
    ax.set_xticks(np.arange(-0.5, len(cols), 1), minor=True)
    ax.set_yticks(np.arange(-0.5, len(df), 1), minor=True)
    ax.grid(which="minor", color="white", linewidth=0.8)
    ax.tick_params(which="minor", bottom=False, left=False)
    for spine in ax.spines.values():
        spine.set_visible(False)

    for i in range(data.shape[0]):
        for j in range(data.shape[1]):
            value = data[i, j]
            if j == 0:
                txt = f"{value:.1f}"
            elif j == 1:
                txt = f"{value:.2f}" if value >= 1 else f"{value:.3f}"
            elif j in (2, 3):
                txt = f"{value:.3f}"
            else:
                txt = f"{value:.2f}" if value >= 1 else f"{value:.3f}"
            color = "white" if display[i, j] > 0.55 else "black"
            ax.text(j, i, txt, ha="center", va="center", fontsize=6.8, color=color)

    cbar = fig.colorbar(im, ax=ax, fraction=0.025, pad=0.012)
    cbar.set_ticks([0, 1])
    cbar.set_ticklabels(["low", "high"])
    cbar.ax.tick_params(labelsize=7, length=0)
    cbar.outline.set_visible(False)
    cbar.set_label("within-column", fontsize=7)

    fig.tight_layout(pad=0.2)
    save(fig, out_prefix)
    plt.close(fig)


def figure_c(df: pd.DataFrame, out_prefix: Path) -> None:
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    plt.rcParams.update(
        {
            "font.size": 8,
            "axes.titlesize": 8.5,
            "axes.labelsize": 8,
            "xtick.labelsize": 7.5,
            "ytick.labelsize": 7.5,
            "pdf.fonttype": 42,
            "ps.fonttype": 42,
        }
    )

    top_mu = df.sort_values("fisher_mass_per_param_ckpt10", ascending=False).head(3).copy()
    top_delta = df.sort_values("js_drift_per_param_5_to_10", ascending=False).head(3).copy()

    fig, axes = plt.subplots(1, 2, figsize=(5.7, 1.85), gridspec_kw={"wspace": 0.55})
    for ax, data, value_col, xlabel, title in [
        (axes[0], top_mu, "fisher_mean_x1e5_ckpt10", r"$10^5\,\mu_g$", "top Fisher/param"),
        (axes[1], top_delta, "js_per_param_x1e7_5_to_10", r"$10^7\,d_{\mathrm{JS}}/N_g$", "top drift/param 5→10"),
    ]:
        data = data.iloc[::-1]
        y = np.arange(len(data))
        colors = ["#F58518" if g == "final_heads" else "#72B7B2" if g.startswith("decoder") else "#4C78A8" for g in data["group"]]
        vals = data[value_col].to_numpy()
        ax.barh(y, vals, color=colors, edgecolor="0.25", linewidth=0.35)
        ax.set_yticks(y)
        ax.set_yticklabels(data["label"])
        ax.set_xlabel(xlabel)
        ax.set_title(title)
        ax.set_xlim(0, max(vals) * 1.18)
        for yi, value in enumerate(vals):
            ax.text(value + max(vals) * 0.025, yi, f"{value:.2f}" if value >= 1 else f"{value:.3f}", va="center", fontsize=7)
        clean_axes(ax)

    save(fig, out_prefix)
    plt.close(fig)


def write_summary(df: pd.DataFrame, report: Path) -> None:
    caption = (
        "Post-hoc Fisher diagnostic on the KLT full fine-tuning probe. "
        "Panel (a) shows checkpoint-10 Fisher mass, highlighting total task sensitivity in encoder MLP and attention groups. "
        "Panel (b) shows Fisher mass per parameter, where final decoder heads provide the strongest parameter-normalized signal. "
        "Panel (c) shows Jensen--Shannon Fisher drift per parameter for checkpoint transitions 1→5 and 5→10. "
        "The diagnostic is used to interpret PEFT placement, not to select the final model."
    )
    paragraph = (
        "The Fisher diagnostic supports different aspects of the selected PEFT design. "
        "At checkpoint 10, total Fisher mass is concentrated in the encoder MLP and attention groups, consistent with placing AdaptFormer modules in MLP blocks and LoRA in the attention QKV pathway. "
        "In contrast, final decoder heads have the strongest Fisher mass per parameter among the analyzed PEFT-relevant groups, supporting final-head tuning as an efficient decoder adaptation target. "
        "The JS drift view shows that parameter-normalized drift also favors final heads within these PEFT-relevant groups, although raw drift is larger in broader decoder branches. "
        "Thus, Fisher is best interpreted as post-hoc support for adapter placement, while final model choice remains determined by the ablation results."
    )

    table_cols = [
        "group",
        "param_count",
        "fisher_mass_percent_ckpt10",
        "fisher_mean_x1e5_ckpt10",
        "js_per_param_x1e7_1_to_5",
        "js_per_param_x1e7_5_to_10",
    ]
    table = df[table_cols].copy()
    table["group"] = table["group"].map(GROUP_LABELS)
    markdown_table = table.to_markdown(index=False, floatfmt=".4f")

    lines = [
        "# Fisher figures summary",
        "",
        "Generated from audited values in `reports/fisher_interpretation_audit_values.csv`.",
        "",
        "## Outputs",
        "",
        "- `figures/fisher_workshop_main_panel.pdf` / `.png`",
        "- `figures/fisher_workshop_supp_heatmap.pdf` / `.png`",
        "- `figures/fisher_workshop_supp_top3.pdf` / `.png`",
        "",
        "## Values used",
        "",
        markdown_table,
        "",
        "## Proposed Figure A caption",
        "",
        caption,
        "",
        "## Recommended Results paragraph",
        "",
        paragraph,
        "",
    ]
    report.parent.mkdir(parents=True, exist_ok=True)
    report.write_text("\n".join(lines))


def main() -> None:
    args = parse_args()
    df = load_focus(args.audit_csv)
    args.fig_dir.mkdir(parents=True, exist_ok=True)

    figure_a(df, args.fig_dir / "fisher_workshop_main_panel")
    figure_b(df, args.fig_dir / "fisher_workshop_supp_heatmap")
    figure_c(df, args.fig_dir / "fisher_workshop_supp_top3")
    write_summary(df, args.report)

    print(f"Wrote {args.fig_dir / 'fisher_workshop_main_panel.pdf'}")
    print(f"Wrote {args.fig_dir / 'fisher_workshop_supp_heatmap.pdf'}")
    print(f"Wrote {args.fig_dir / 'fisher_workshop_supp_top3.pdf'}")
    print(f"Wrote {args.report}")


if __name__ == "__main__":
    main()
