sthelar_root: ${STHELAR_ROOT}
output_root: ${DATA_ROOT}/sthelar20x_multitissue_scan_5class

tissue_name: MultiTissue

slide_ids:
  - breast_s0
  - breast_s1
  - breast_s3
  - breast_s6
  - cervix_s0
  - colon_s1
  - colon_s2
  - heart_s0
  - kidney_s0
  - kidney_s1
  - liver_s0
  - liver_s1
  - lung_s1
  - lung_s3
  - lymph_node_s0
  - ovary_s0
  - ovary_s1
  - pancreatic_s0
  - pancreatic_s1
  - pancreatic_s2
  - prostate_s0
  - skin_s1
  - skin_s2
  - skin_s3
  - skin_s4
  - tonsil_s0
  - tonsil_s1

strategy: auto
split_axis: x
boundary_margin: 64

train_frac: 0.70
valid_frac: 0.15
test_frac: 0.15

train_frac_inside_train_slide: 0.85
valid_frac_inside_train_slide: 0.15

max_patches_per_slide: 500
max_per_split: null

random_seed: 42
overwrite: true

label_mode: 5class
label_column: cells_final_label_group
ignore_labels: null

nuclei_types:
  Background: 0
  Immune: 1
  Stromal: 2
  Epithelial: 3
  Other: 4

label_mapping:
  T_NK: Immune
  B_Plasma: Immune
  Myeloid: Immune
  Blood_vessel: Stromal
  Fibroblast_Myofibroblast: Stromal
  Epithelial: Epithelial
  Melanocyte: Other
  Specialized: Other
  Other: Other

fallback_class: Other