sthelar_root: STHELAR_ROOT
output_root: DATA_ROOT/sthelar40x_kidney_5class_spatial_margin128
tissue_name: Kidney
tissue: kidney
slide_ids:
  - kidney_s0
  - kidney_s1
strategy: spatial
train_slides:
  - kidney_s0
  - kidney_s1
valid_slides: []
test_slides: []
split_axis: x
boundary_margin: 128
train_frac: 0.7
valid_frac: 0.15
test_frac: 0.15
train_frac_inside_train_slide: 0.85
valid_frac_inside_train_slide: 0.15
max_patches_per_slide: null
max_per_split: null
random_seed: 42
overwrite: false
keep_tmp: false
label_mode: 5class
label_column: cells_final_label_group
ignore_labels: null
nuclei_types:
  Background: 0
  Immune: 1
  Stromal: 2
  Epithelial: 3
  Melanocyte: 4
  Other: 5
label_mapping:
  T_NK: Immune
  B_Plasma: Immune
  Myeloid: Immune
  Blood_vessel: Stromal
  Fibroblast_Myofibroblast: Stromal
  Epithelial: Epithelial
  Melanocyte: Melanocyte
  Specialized: Other
  Other: Other
fallback_class: Other

