adapters:
  adapter_type: fullft
logging:
  mode: offline
  project: sthelar40x_tissue_specific_fullft
  notes: Full fine-tuning on the STHELAR 40x pancreatic 5-class spatial margin128
    cap50000 dataset.
  log_comment: sthelar40x_pancreatic_5class_spatial_margin128_cap50000_fullft_lr1e-5_e10_seed42_CLEAN
  tags:
  - sthelar
  - 40x
  - pancreatic
  - tissue_specific
  - spatial_margin128
  - margin128
  - cap50000
  - 5class
  - fullft
  - lr1e-5
  - e10
  - seed42
  - clean
  wandb_dir: run/sthelar40x_pancreatic_5class_spatial_margin128_cap50000_fullft_lr1e-5_e10_seed42_CLEAN/wandb
  log_dir: run/sthelar40x_pancreatic_5class_spatial_margin128_cap50000_fullft_lr1e-5_e10_seed42_CLEAN/log
  level: debug
  log_images: false
random_seed: 42
gpu: 0
data:
  dataset: STHELAR
  dataset_path: ${DATA_ROOT}/sthelar40x_pancreatic_5class_spatial_margin128_cap50000
  label_mode: 5class
  split: spatial
  train_folds:
  - train
  val_folds:
  - valid
  test_folds:
  - test
  num_nuclei_classes: 6
  num_tissue_classes: 1
  input_shape: 256
  magnification: 40
model:
  backbone: SAM-H
  pretrained_encoder: null
  pretrained: models/pretrained/CellViT-SAM-H-x40.pth
  embed_dim: 1280
  input_channels: 3
  depth: 32
  num_heads: 16
  extract_layers: 4
  shared_decoders: false
training:
  batch_size: 4
  epochs: 10
  unfreeze_epoch: 0
  optimizer: AdamW
  optimizer_hyperparameter:
    lr: 1.0e-05
    betas:
    - 0.85
    - 0.85
  early_stopping_patience: 10
  scheduler:
    scheduler_type: exponential
  sampling_strategy: cell
  sampling_gamma: 0.85
  mixed_precision: true
  eval_every: 1
  unfreeze_encoder: true
checkpointing:
  save_best: true
  save_last: true
  keep_last_n: 1
  save_every: 1
  delete_intermediate_checkpoints: true
transformations:
  randomrotate90:
    p: 0.5
  horizontalflip:
    p: 0.5
  verticalflip:
    p: 0.5
  downscale:
    p: 0.5
    scale: 0.2
  blur:
    p: 0.5
    blur_limit: 10
  gaussnoise:
    p: 0.5
    var_limit: 10
  colorjitter:
    p: 0.5
    scale_setting: 0.25
    scale_color: 0.1
  superpixels:
    p: 0.5
  zoomblur:
    p: 0.5
  randomsizedcrop:
    p: 0.5
  elastictransform:
    p: 0.5
  normalize:
    mean:
    - 0.5
    - 0.5
    - 0.5
    std:
    - 0.5
    - 0.5
    - 0.5
eval_checkpoint: latest_checkpoint.pth
inference:
  qc_jaccard_thresholds:
  - 0.45
  - 0.6
  - 0.7
  - 0.8
